


set_property PACKAGE_PIN D18 [get_ports {do_out_0[15]}]
set_property PACKAGE_PIN G14 [get_ports {do_out_0[14]}]
set_property PACKAGE_PIN M15 [get_ports {do_out_0[13]}]
set_property PACKAGE_PIN M14 [get_ports {do_out_0[12]}]
set_property PACKAGE_PIN R17 [get_ports {do_out_0[11]}]
set_property PACKAGE_PIN T17 [get_ports {do_out_0[10]}]
set_property PACKAGE_PIN R18 [get_ports {do_out_0[9]}]
set_property PACKAGE_PIN V17 [get_ports {do_out_0[8]}]
set_property PACKAGE_PIN V18 [get_ports {do_out_0[7]}]
set_property PACKAGE_PIN W18 [get_ports {do_out_0[6]}]
set_property PACKAGE_PIN W19 [get_ports {do_out_0[5]}]
set_property PACKAGE_PIN N17 [get_ports {do_out_0[4]}]
set_property PACKAGE_PIN P18 [get_ports {do_out_0[3]}]
set_property PACKAGE_PIN P15 [get_ports {do_out_0[2]}]
set_property PACKAGE_PIN P16 [get_ports {do_out_0[1]}]
set_property PACKAGE_PIN T19 [get_ports {do_out_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {do_out_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports Vaux15_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux15_0_v_p]
set_property PACKAGE_PIN J16 [get_ports Vaux15_0_v_n]
set_property PACKAGE_PIN K16 [get_ports Vaux15_0_v_p]


set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux7_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux7_0_v_p]

set_property IOSTANDARD LVCMOS33 [get_ports Vaux14_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux14_0_v_p]
set_property PACKAGE_PIN N16 [get_ports Vaux14_0_v_n]
set_property PACKAGE_PIN N15 [get_ports Vaux14_0_v_p]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
