set_property PACKAGE_PIN G15 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports {divisor[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {divisor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {divisor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {divisor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {divisor[0]}]
set_property PACKAGE_PIN P15 [get_ports {divisor[0]}]
set_property PACKAGE_PIN W13 [get_ports {divisor[1]}]
set_property PACKAGE_PIN T16 [get_ports {divisor[2]}]
set_property PACKAGE_PIN K18 [get_ports {divisor[3]}]
set_property PACKAGE_PIN P16 [get_ports {divisor[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports dir]
set_property PACKAGE_PIN Y16 [get_ports dir]

set_property IOSTANDARD LVCMOS33 [get_ports {encout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {encout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {encout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {encout[0]}]
set_property PACKAGE_PIN M14 [get_ports {encout[0]}]
set_property PACKAGE_PIN M15 [get_ports {encout[1]}]
set_property PACKAGE_PIN G14 [get_ports {encout[2]}]
set_property PACKAGE_PIN D18 [get_ports {encout[3]}]


set_property IOSTANDARD LVCMOS33 [get_ports {incenc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {incenc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {incenc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {incenc[0]}]
set_property PACKAGE_PIN T14 [get_ports {incenc[0]}]
set_property PACKAGE_PIN T15 [get_ports {incenc[1]}]
set_property PACKAGE_PIN P14 [get_ports {incenc[2]}]
set_property PACKAGE_PIN R14 [get_ports {incenc[3]}]


set_property SLEW FAST [get_ports {encout[3]}]
set_property SLEW FAST [get_ports {encout[2]}]
set_property SLEW FAST [get_ports {encout[1]}]
set_property SLEW FAST [get_ports {encout[0]}]
set_property SLEW FAST [get_ports {incenc[3]}]
set_property SLEW FAST [get_ports {incenc[2]}]
set_property SLEW FAST [get_ports {incenc[1]}]
set_property SLEW FAST [get_ports {incenc[0]}]
